//ACTIONS_TYPES:
const GET_USERS = 'GET_USERS';
const DELETE_USER = 'DELETE_USER';
const ADD_USER = 'ADD_USER';
const GET_SINGLE_USER = 'GET_SINGLE_USER';
const UPDATE_USER = 'UPDATE_USER';

export { GET_USERS, DELETE_USER, ADD_USER, GET_SINGLE_USER, UPDATE_USER };
